from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle

ROOT = Path(__file__).parent
OUT = ROOT / 'output' / 'pdf' / 'guia_estudo_case_python.pdf'
OUT.parent.mkdir(parents=True, exist_ok=True)
pdfmetrics.registerFont(TTFont('Arial', r'C:\Windows\Fonts\arial.ttf'))
pdfmetrics.registerFont(TTFont('Arial-Bold', r'C:\Windows\Fonts\arialbd.ttf'))

NAVY, BLUE, INK, MUTED = '#123047', '#1B6CA8', '#1E2933', '#586774'
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='TitleX', fontName='Arial-Bold', fontSize=25, leading=31, textColor=NAVY, alignment=1, spaceAfter=14))
styles.add(ParagraphStyle(name='SubX', fontName='Arial', fontSize=12, leading=17, textColor=MUTED, alignment=1, spaceAfter=22))
styles.add(ParagraphStyle(name='H1X', fontName='Arial-Bold', fontSize=17, leading=22, textColor=NAVY, spaceBefore=8, spaceAfter=8))
styles.add(ParagraphStyle(name='H2X', fontName='Arial-Bold', fontSize=12.5, leading=16, textColor=BLUE, spaceBefore=7, spaceAfter=5))
styles.add(ParagraphStyle(name='BodyX', fontName='Arial', fontSize=10.2, leading=14.5, textColor=INK, spaceAfter=7))
styles.add(ParagraphStyle(name='SmallX', fontName='Arial', fontSize=8.4, leading=11, textColor=INK))
styles.add(ParagraphStyle(name='CodeX', fontName='Courier', fontSize=8.3, leading=11, textColor=INK, backColor='#F2F5F7', borderColor='#D8E1E7', borderWidth=.4, borderPadding=7, spaceAfter=9))

def P(text, style='BodyX'): return Paragraph(text, styles[style])
def B(text): return P('&bull; ' + text)
def C(text): return P(text.replace('\n', '<br/>'), 'CodeX')
def box(title, text, color='#EAF3F8'):
    t = Table([[P('<b>' + title + '</b><br/>' + text)]], colWidths=[17.1*cm])
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),color),('BOX',(0,0),(-1,-1),.6,BLUE),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]))
    return t
def T(head, rows, widths):
    data = [[P('<b>'+x+'</b>','SmallX') for x in head]] + [[P(x,'SmallX') for x in r] for r in rows]
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.35,'#C9D6DF'),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,'#F7FAFC']),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
    return t
def foot(canv, doc):
    canv.saveState(); canv.setStrokeColor('#D4E0E7'); canv.line(1.6*cm,1.35*cm,A4[0]-1.6*cm,1.35*cm)
    canv.setFont('Arial',8); canv.setFillColor(MUTED); canv.drawString(1.6*cm,.9*cm,'Guia de estudo - Case técnico Python'); canv.drawRightString(A4[0]-1.6*cm,.9*cm,'Página %d' % doc.page); canv.restoreState()

s=[]
s += [Spacer(1,2.2*cm),P('Guia de estudo','TitleX'),P('Case técnico de Python - preparação para conversa com o CEO','SubX'),box('Como usar','Leia as quatro primeiras páginas para entender a lógica. Depois pratique as respostas de entrevista em voz alta. A última página é uma revisão de 2 minutos.' ,'#E8F5EC'),Spacer(1,.45*cm),P('O que esta case avalia','H1X')]
s.append(T(['Ponto','Problema','Habilidade'],[['1','Somar dados de um JSON imperfeito','Qualidade, validação e conversão de dados'],['2','Comparar textos em codificações diferentes','Bytes, codificação e comparação'],['3 a 6','Calcular dias entre datas','Biblioteca padrão e calendário']],[1.5*cm,8*cm,7.6*cm]))
s += [Spacer(1,.3*cm),P('A ideia central','H2X'),P('A case não mede apenas se você chega ao número final. Ela mede se entende a natureza do dado antes de processá-lo. Um dado pode falhar por formato, tipo, codificação ou regra de calendário. A sequência correta é: <b>ler, normalizar, validar e só então calcular ou comparar</b>.'),P('Vocabulário mínimo','H2X'),B('<b>Variável:</b> nome que guarda um valor, como <font name="Courier">ano</font>.'),B('<b>Função:</b> bloco reutilizável, como <font name="Courier">calcular_dias(ano)</font>.'),B('<b>JSON:</b> formato de texto usado para troca de dados entre sistemas.'),B('<b>Exceção:</b> erro previsto e tratado para o programa não falhar sem explicação.')]
s.append(PageBreak())
s += [P('1. Estrutura da solução','H1X'),P('O README separa a entrega em três programas pequenos. Isso mantém cada responsabilidade isolada, facilita testes e torna a explicação mais clara.'),T(['Arquivo','Função','Resultado'],[['ponto1.py','Lê o JSON, corrige aspas e soma valores.','10'],['ponto2.py','Lê bytes, decodifica e compara textos.','mesmo conteúdo'],['pontos3_a_6.py','Monta datas e calcula a diferença.','243, 242, 242, 242']],[3.4*cm,10*cm,3.7*cm]),P('Como comunicar a arquitetura','H2X'),box('Resposta curta','Eu dividi os problemas por responsabilidade. Cada arquivo trata um tipo de dado e usa a biblioteca padrão adequada. Isso deixa a solução simples, verificável e fácil de explicar.'),P('2. Ponto 1 - JSON e soma','H1X'),P('A entrada é <font name="Courier">[1, “2”, 3, “4”]</font>. A resposta é 10, mas há dois problemas: as aspas são tipográficas e dois números estão como texto. JSON aceita aspas retas, não aspas tipográficas.'),C('texto = caminho.read_text(encoding="utf-8-sig")\ntexto = texto.replace("“", \'"\').replace("”", \'"\')\ndados = json.loads(texto)\nnumeros = [int(valor) for valor in dados]\nreturn sum(numeros)'),P('Linha a linha','H2X'),B('<font name="Courier">read_text</font> lê o arquivo. <font name="Courier">utf-8-sig</font> também tolera um marcador invisível inicial.'),B('<font name="Courier">replace</font> troca caracteres inválidos pelas aspas aceitas pelo JSON.'),B('<font name="Courier">json.loads</font> transforma texto em uma lista Python.'),B('<font name="Courier">int(valor)</font> converte <font name="Courier">"2"</font> em <font name="Courier">2</font>; texto e número não são o mesmo tipo.'),B('<font name="Courier">sum</font> agrega 1 + 2 + 3 + 4 = 10.')]
s.append(PageBreak())
s += [P('Como defender o ponto 1','H2X'),box('Resposta-modelo','Antes de calcular, eu garanto que o dado esteja em um formato confiável. A solução corrige o problema conhecido de formatação, valida que a estrutura é uma lista e converte os valores para o tipo numérico antes de somar.'),P('3. Ponto 2 - textos, bytes e codificação','H1X'),P('O conceito-chave é: <b>bytes não são texto</b>. O arquivo guarda bytes; eles só representam letras quando aplicamos uma codificação. Os arquivos têm bytes diferentes, mas viram o mesmo texto após decodificação correta.'),T(['Arquivo','Caractere final','Bytes','Codificação'],[['test2_text1.txt','è!?','C3 A8 21 3F','UTF-8'],['test2_text2.txt','è!?','E8 21 3F','Windows-1252 / Latin-1']],[4.2*cm,3.4*cm,4.7*cm,5.2*cm]),C('dados = caminho.read_bytes()\nfor encoding in ("utf-8", "cp1252", "latin-1"):\n    try:\n        return dados.decode(encoding)\n    except UnicodeDecodeError:\n        continue'),P('Linha a linha','H2X'),B('<font name="Courier">read_bytes</font> lê o conteúdo bruto, sem assumir codificação.'),B('O código tenta UTF-8, depois <font name="Courier">cp1252</font> (comum no Windows) e Latin-1.'),B('<font name="Courier">UnicodeDecodeError</font> é o erro esperado se aqueles bytes não pertencem à codificação tentada.'),B('<font name="Courier">texto1 == texto2</font> verifica texto igual e na mesma ordem.'),B('<font name="Courier">Counter(texto1) == Counter(texto2)</font> verifica que cada caractere, espaço e pontuação aparece a mesma quantidade de vezes.'),box('Como defender','Eu não compararia bytes diretamente: o mesmo conteúdo pode ser armazenado de maneiras diferentes. Primeiro converto ambos para uma representação textual comum; só então comparo o significado do conteúdo.')]
s.append(PageBreak())
s += [P('4. Pontos 3 a 6 - datas e anos bissextos','H1X'),P('O programa cria 15 de fevereiro e 15 de outubro de cada ano. A subtração de datas é delegada à biblioteca padrão do Python.'),C('inicio = date(ano, 2, 15)\nfim = date(ano, 10, 15)\nreturn (fim - inicio).days'),P('O resultado é a quantidade de dias transcorridos entre as datas. O dia inicial não conta como dia completo transcorrido.'),T(['Ano','Dias','Explicação'],[['2000','243','É bissexto; 29 de fevereiro existe no intervalo.'],['2001','242','Não é divisível por 4.'],['1900','242','É divisível por 100, mas não por 400.'],['1582','242','Python usa calendário gregoriano contínuo.']],[2.8*cm,2.3*cm,12.4*cm]),P('Regra de ano bissexto','H2X'),B('Divisível por 4: normalmente é bissexto.'),B('Divisível por 100: deixa de ser bissexto.'),B('Divisível por 400: volta a ser bissexto.'),P('O contraste entre 2000 e 1900 foi incluído para testar a exceção dos anos centenários.'),box('Atenção ao ano 1582','Historicamente, os países adotaram o calendário gregoriano em momentos diferentes. Python não modela essa transição local: datetime usa calendário gregoriano proléptico. Para o teste, essa é a convenção correta; num produto histórico, a premissa precisaria ser discutida.','#FFF4D8')]
s.append(PageBreak())
s += [P('5. Simulação de entrevista','H1X'),P('Pratique as respostas em voz alta. O objetivo é mostrar lógica, clareza e consciência dos limites da solução.'),P('Qual foi sua abordagem geral?','H2X'),box('Resposta-modelo','Eu dividi a entrega por tipo de problema. No primeiro caso tratei formato e tipo de dado; no segundo, codificação de texto; no terceiro, regras de data. Em todos, a sequência foi normalizar, validar e calcular usando a biblioteca padrão.'),P('Por que não usar apenas uma soma no JSON?','H2X'),box('Resposta-modelo','Porque o arquivo não era JSON válido e misturava números com textos. Somar diretamente poderia falhar ou esconder um problema de qualidade. Primeiro corrijo a estrutura, faço o parsing e converto explicitamente os valores.'),P('Como dois arquivos têm o mesmo texto e bytes diferentes?','H2X'),box('Resposta-modelo','A codificação define como um caractere vira bytes. O è ocupa dois bytes em UTF-8 e um byte em Windows-1252. Depois da decodificação correta, o texto representado é o mesmo.'),P('Por que usar Counter além de ==?','H2X'),box('Resposta-modelo','A igualdade verifica texto e ordem. Counter verifica uma hipótese diferente: se a frequência de cada caractere é igual, sem depender da ordem. Na case os dois testes retornam verdadeiro.'),P('O que o caso de 1900 prova?','H2X'),box('Resposta-modelo','Que não basta ser múltiplo de quatro. Anos múltiplos de cem só são bissextos se também forem múltiplos de quatrocentos. Por isso 1900 não adiciona 29 de fevereiro.')]
s.append(PageBreak())
s += [P('6. Perguntas de aprofundamento','H1X'),T(['Pergunta','Boa resposta'],[['Que melhoria faria em produção?','Definiria UTF-8 como contrato de integração, registraria desvios e validaria tipos do JSON mais estritamente.'],['A troca de aspas sempre é segura?','É adequada porque o exercício revela um problema conhecido. Em produção, eu limitaria a normalização ao contexto esperado e registraria a alteração.'],['Counter ignora espaços?','Não. Inclui espaços, pontuação e quebras de linha.'],['Python usa o calendário histórico de 1582?','Não exatamente. datetime usa calendário gregoriano proléptico. A resposta depende da convenção da biblioteca.'],['Por que usar biblioteca padrão?','Ela é testada, reduz erro manual e deve ser preferida quando cobre a regra de negócio.']],[6.1*cm,11.4*cm]),P('Erros que você deve evitar','H2X'),B('Não diga que os arquivos eram idênticos em bytes. Eles não eram.'),B('Não diga que todo ano múltiplo de 4 é bissexto. 1900 é o contraexemplo.'),B('Não chame <font name="Courier">"2"</font> de número. É texto que representa um número.'),B('Não afirme que 1582 reproduz a história de todos os países.'),box('Frase de maturidade','Em produção, eu deixaria as premissas explícitas e criaria testes para entradas inválidas, codificações inesperadas e datas de fronteira. A resposta correta depende tanto da regra de negócio quanto do algoritmo.','#E8F5EC')]
s.append(PageBreak())
s += [P('Revisão final - 2 minutos','H1X'),box('A narrativa em 30 segundos','A case trata três fontes comuns de erro: formato de dados, codificação de texto e regra de calendário. Eu normalizei e validei os dados antes de operá-los, usei bibliotecas padrão e deixei explícitas as premissas.','#E8F5EC'),P('Resultados para memorizar','H2X'),T(['Ponto','Resposta','Por quê'],[['JSON','10','Corrige aspas, faz parsing, converte textos numéricos e soma.'],['Textos','Iguais após decodificação','UTF-8 e CP1252 guardam è em bytes diferentes.'],['2000','243 dias','É bissexto.'],['2001','242 dias','Não é bissexto.'],['1900','242 dias','Século não divisível por 400.'],['1582','242 dias','Calendário contínuo do Python.']],[3.2*cm,4.3*cm,9.6*cm]),P('Frases para lembrar','H2X'),B('Formato primeiro, cálculo depois.'),B('Bytes não são texto; codificação dá significado aos bytes.'),B('Texto e número são tipos diferentes.'),B('Explique premissas, não apenas resultados.'),P('Fechamento sugerido','H2X'),box('Resposta final','O principal aprendizado é que qualidade de dados não é uma etapa separada do problema: ela faz parte da solução. Antes de somar, comparar ou calcular datas, é preciso garantir que estamos interpretando corretamente o dado que recebemos.')]

doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=1.7*cm,leftMargin=1.7*cm,topMargin=1.55*cm,bottomMargin=1.8*cm,title='Guia de estudo - Case técnico Python',author='Codex')
doc.build(s,onFirstPage=foot,onLaterPages=foot)
print(OUT)
